// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nexrpmlnxeapkixlrbhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5leHJwbWxueGVhcGtpeGxyYmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODg1NTEsImV4cCI6MjA3Mzg2NDU1MX0._D4ztC24PIUgeWReuxv7tPGFQX2M4gur_CLMM44kkc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});